spring.application.name=Gestion_Botica


# URL de conexión (Pooler de Supabase)
#spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
#spring.datasource.username=postgres.wjwmbaywuropkwbugrzb
#spring.datasource.password=bbV5rxsQ1o6zMKRW
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA (Usamos 'validate' porque las tablas ya existen en Supabase)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Desactivar seguridad temporalmente para pruebas iniciales
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
